# Generated by Django 3.2.25 on 2026-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('feedback', models.CharField(max_length=45)),
                ('u_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
