# Generated by Django 3.2.25 on 2026-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=45)),
                ('review', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
