# Generated by Django 3.2.25 on 2026-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appbk',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('doc_id', models.IntegerField()),
                ('doc_name', models.CharField(max_length=45)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'appbk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('sch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('date', models.CharField(max_length=45)),
                ('time', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'doctor_schedule',
                'managed': False,
            },
        ),
    ]
