# Generated by Django 3.2.25 on 2026-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('experience', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
