# Generated by Django 3.2.25 on 2026-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('symptoms', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
    ]
